In [1]:
import pandas as pd

c:\Users\storoeb\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [5]:
df = pd.read_excel(r'C:\Users\storoeb\OneDrive - Milwaukee School of Engineering\Desktop\ai club\e-board\website\maic\data\raffle_parsing\raffle_dfs\MAIC_ Summer Celebration Raffle 2024-2025(1-36).xlsx')

# Grab only the last two columns of the DataFrame
df = df.iloc[:, -2:]
df

      First and Last Name How Many Points Would You Like to Spend?
0          Kathlyn Leaños                                       10
1          Andrew Needham                                        0
2           Alayna Ostler                                        5
3               Alex Toma                                        4
4          Julian Baldwin                                        2
5           Trent Adamson                                        0
6      Wendpanga Tapsoba                                         2
7           Evan Schubert                                        2
8          Sydney Balboni                                        3
9            Alhagie Boye                                        0
10          Leigh Goetsch                                        0
11         Vincenzo Bean                                         0
12       Reagan Burkemper                                        2
13       Travis Jankowski                                        0
14            Ben Paulson                                       27
15           Michael Link                                        0
16           Michael Wood                                        0
17                 Oliver                                        2
18         Jonathan Keane                                   All in
19           Aaron Herbst                                       16
20          Adam Swedlund                                        0
21            Zoe Kirkman                                        1
22       Patrick Rafferty                                        0
23               Andy Dao                                        5
24            Colin Glynn                                        1
25  Charlie BioloThompson                                        4
26       Mikhail Filippov                                        4
27                Hugo gl                                        5
28    Ryan Pal Hilgendorf                                        0
29        Cameron Delpage                                        0
30         Joseph Beattie                                       16
31        Benjamin Leshin                                       12
32            Hayden Park                                        0
33        Konrad Rozpadek                                        5
34           Delsoro Some                                        3
35        Adrian Manchado                                        2

### Create a list that is Easy to Input Into Online Roulette Wheel
https://wheelofnames.com/

In [7]:
# Given the dataframe, create a new dataframe where a name is repeated x number of rows, where x is the number denoted in the second column. If the number is NaN or 0, then inlcude the person only once

# Create a new dataframe
entries = []

# Iterate through each row in the dataframe

for index, row in df.iterrows():
    # Get the name and number of times to repeat
    name = row[-2]
    num = row[-1]
    
    # If the number is NaN or 0, then include the person only once
    if pd.isnull(num) or num == 0:
        entries.append(name)
    else:
        try:
            # Try to convert to int and repeat the person x number of times
            points = int(num)
            for i in range(points + 1):
                entries.append(name)
        except ValueError:
            # If the points column isn't a number, just include the person once
            entries.append(name)

entries

C:\Users\storoeb\AppData\Local\Temp\ipykernel_19452\3041264700.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  name = row[-2]
C:\Users\storoeb\AppData\Local\Temp\ipykernel_19452\3041264700.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  num = row[-1]

['Kathlyn Leaños',
 'Kathlyn Leaños',
 'Kathlyn Leaños',
 'Kathlyn Leaños',
 'Kathlyn Leaños',
 'Kathlyn Leaños',
 'Kathlyn Leaños',
 'Kathlyn Leaños',
 'Kathlyn Leaños',
 'Kathlyn Leaños',
 'Kathlyn Leaños',
 'Andrew Needham',
 'Alayna Ostler',
 'Alayna Ostler',
 'Alayna Ostler',
 'Alayna Ostler',
 'Alayna Ostler',
 'Alayna Ostler',
 'Alex Toma',
 'Alex Toma',
 'Alex Toma',
 'Alex Toma',
 'Alex Toma',
 'Julian Baldwin',
 'Julian Baldwin',
 'Julian Baldwin',
 'Trent Adamson',
 'Wendpanga Tapsoba ',
 'Wendpanga Tapsoba ',
 'Wendpanga Tapsoba ',
 'Evan Schubert',
 'Evan Schubert',
 'Evan Schubert',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Sydney Balboni',
 'Alhagie Boye',
 'Leigh Goetsch',
 'Vincenzo Bean ',
 'Reagan Burkemper',
 'Reagan Burkemper',
 'Reagan Burkemper',
 'Travis Jankowski',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Ben Paulson',
 'Michael Link',
 'Michael Wood',
 'Oliver',
 'Oliver',
 'Oliver',
 'Jonathan Keane',
 'Aaron Herbst',
 'Aaron Herbst',
 'Aaron Herbst',
 'Aaron Herbst',
 'Aaron Herbst',
 'Aaron Herbst',
 'Aaron Herbst',
 'Aaron Herbst',
 'Aaron Herbst',
 'Aaron Herbst',
 'Aaron Herbst',
 'Aaron Herbst',
 'Aaron Herbst',
 'Aaron Herbst',
 'Aaron Herbst',
 'Aaron Herbst',
 'Aaron Herbst',
 'Adam Swedlund',
 'Zoe Kirkman',
 'Zoe Kirkman',
 'Patrick Rafferty',
 'Andy Dao',
 'Andy Dao',
 'Andy Dao',
 'Andy Dao',
 'Andy Dao',
 'Andy Dao',
 'Colin Glynn',
 'Colin Glynn',
 'Charlie BioloThompson',
 'Charlie BioloThompson',
 'Charlie BioloThompson',
 'Charlie BioloThompson',
 'Charlie BioloThompson',
 'Mikhail Filippov',
 'Mikhail Filippov',
 'Mikhail Filippov',
 'Mikhail Filippov',
 'Mikhail Filippov',
 'Hugo gl',
 'Hugo gl',
 'Hugo gl',
 'Hugo gl',
 'Hugo gl',
 'Hugo gl',
 'Ryan Pal Hilgendorf',
 'Cameron Delpage',
 'Joseph Beattie',
 'Joseph Beattie',
 'Joseph Beattie',
 'Joseph Beattie',
 'Joseph Beattie',
 'Joseph Beattie',
 'Joseph Beattie',
 'Joseph Beattie',
 'Joseph Beattie',
 'Joseph Beattie',
 'Joseph Beattie',
 'Joseph Beattie',
 'Joseph Beattie',
 'Joseph Beattie',
 'Joseph Beattie',
 'Joseph Beattie',
 'Joseph Beattie',
 'Benjamin Leshin',
 'Benjamin Leshin',
 'Benjamin Leshin',
 'Benjamin Leshin',
 'Benjamin Leshin',
 'Benjamin Leshin',
 'Benjamin Leshin',
 'Benjamin Leshin',
 'Benjamin Leshin',
 'Benjamin Leshin',
 'Benjamin Leshin',
 'Benjamin Leshin',
 'Benjamin Leshin',
 'Hayden Park',
 'Konrad Rozpadek',
 'Konrad Rozpadek',
 'Konrad Rozpadek',
 'Konrad Rozpadek',
 'Konrad Rozpadek',
 'Konrad Rozpadek',
 'Delsoro Some',
 'Delsoro Some',
 'Delsoro Some',
 'Delsoro Some',
 'Adrian Manchado',
 'Adrian Manchado',
 'Adrian Manchado']

### Better DF Format
Get the df into a format which is easy to remove the points from the online leaderboard

In [14]:
# For df, replace all Nan values with 0 (Free point)
df = df.fillna(0)

# Rename the first column to 'Name' and the second column to 'Points'
df.columns = ['Name', 'Points']
df

# For each name, get rid of white space surrounding the name and title the string
df['Name'] = df['Name'].str.strip().str.title()
df

                     Name  Points
0          Kathlyn Leaños      10
1          Andrew Needham       0
2           Alayna Ostler       5
3               Alex Toma       4
4          Julian Baldwin       2
5           Trent Adamson       0
6       Wendpanga Tapsoba       2
7           Evan Schubert       2
8          Sydney Balboni       3
9            Alhagie Boye       0
10          Leigh Goetsch       0
11          Vincenzo Bean       0
12       Reagan Burkemper       2
13       Travis Jankowski       0
14            Ben Paulson      27
15           Michael Link       0
16           Michael Wood       0
17                 Oliver       2
18         Jonathan Keane  All in
19           Aaron Herbst      16
20          Adam Swedlund       0
21            Zoe Kirkman       1
22       Patrick Rafferty       0
23               Andy Dao       5
24            Colin Glynn       1
25  Charlie Biolothompson       4
26       Mikhail Filippov       4
27                Hugo Gl       5
28    Ryan Pal Hilgendorf       0
29        Cameron Delpage       0
30         Joseph Beattie      16
31        Benjamin Leshin      12
32            Hayden Park       0
33        Konrad Rozpadek       5
34           Delsoro Some       3
35        Adrian Manchado       2

In [15]:
# Drop the row with "Jonathan Keane" who has "All in" in the Points column
df = df[df['Name'] != 'Jonathan Keane']

# Verify the row was dropped
print(f"Total rows after dropping Jonathan Keane: {len(df)}")

Total rows after dropping Jonathan Keane: 35

In [16]:
user_data = pd.read_csv('../../data/User_Data.csv')
user_data

,User,Description,Awards,All-Time Points,Current Points,First Name,Last Name
0,Ben Paulson,test description,Hacksgiving|ROSIE Competition Finalist 2024|NV...,27,27,Ben,Paulson
1,Lucas Gral,test description,Overlord|eboard2022|eboard2023|eboard2024|2022...,39,39,Lucas,Gral
2,Sydney Balboni,test description,ROSIE Presenter|Hacksgiving|2024 Researcher|20...,53,3,Sydney,Balboni
3,John Cisler,test description,Hacksgiving|ROSIE Competition Finalist 2024|RO...,15,14,John,Cisler
4,Evan Schubert,test description,2024 Researcher|2024 MICS Attendee|2025 MICS A...,16,16,Evan,Schubert
...,...,...,...,...,...,...,...
366,Charles Biolothompson,test description,NaN,3,2,NaN,NaN
367,Marie Diffley,test description,NaN,1,0,NaN,NaN
368,Ben Williams,test description,NVIDIA DLI,2,2,NaN,NaN
369,Joseph Loduca,test description,NVIDIA DLI,2,2,NaN,NaN
370,Joshua Myers,test description,NaN,2,2,NaN,NaN

In [17]:
user_data[user_data['User'] == 'Caleb Gray']

,User,Description,Awards,All-Time Points,Current Points,First Name,Last Name
141,Caleb Gray,test description,2024 Researcher|2024 MICS Attendee|ROSIE Compe...,40,30,Caleb,Gray

In [21]:
# Given the amount of points associated with each Name in df, remove those points from user_data 'Current Points'
for index, row in df.iterrows():
    name = row['Name']
    points = row['Points']
    
    # Find the index of the name in user_data
    user_index = user_data[user_data['User'] == name]

    # If user index empty, skip
    if user_index.empty:
        continue

    # Get the index of the user
    user_index = user_index.index[0]
    
    # Convert points to integer to avoid type mismatch
    points = int(points)
    
    # Subtract the points from the 'Current Points' column
    user_data.loc[user_index, 'Current Points'] = user_data.loc[user_index, 'Current Points'] - points

user_data[user_data['User'] == 'Christian Zastrow']

,User,Description,Awards,All-Time Points,Current Points,First Name,Last Name
147,Christian Zastrow,test description,Hacksgiving|NVIDIA DLI|2024 Researcher,11,3,Christian,Zastrow

In [22]:
user_data.to_csv('../../data/User_Data.csv', index=False)